server:
  port: 9097

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: assim
    password: root
  mail:
    username: aslihan.mert19@gmail.com
    password: mwum xcwi qble kyrc
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

