package com.java14.utility.enums;

public enum EEquipmentType {
    BILGISAYAR, TELEFON, TABLET, KULAKLIK,
    KLAVYE, FARE, MONITOR, YAZICI,  DOSYA_DOLABI,
    KIRTASIYE, LAPTOP_CANTASI,  USB_FLASH_BELLEK,

}
