
server:
  port: 9092

spring:
  data:
    mongodb:
      host: localhost
      port: 27027
      database: managerdb
      username: admin
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: assim
    password: root


