
server:
  port: 9098

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HRPNecessityDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: assim
    password: root


