
server:
  port: 9093

spring:
  data:
    mongodb:
      host: localhost
      port: 27027
      database: companydb
      username: admin
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: assim
    password: root


